image: Visual Studio 2015

environment:
  matrix:
  - ARCH: x64
  - ARCH: x86
    
clone_depth: 1

platform:
  - x64

build_script:
  - call "utils\win\build.bat"

artifacts:
  - path: 'multidir-installer-*.exe'
    name: installer

deploy:
  - provider: GitHub
    description: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: NnyUV44yNAx8ea1L46dVhE4kQxUGd5M1O+yVk+9ncsNHWtw/9JoCnDqNybnxTccP
    artifact: installer
    force_update: true
    on:
      appveyor_repo_tag: true
