workspace:
  base: /base
  path: src
  
pipeline:
  test:
    image: multidir/precise
    commands:
      - mkdir /base/build && cd /base/build
      - /base/src/utils/make_ubuntu.sh

  pack:
    image: multidir/precise
    environment:
      - DISTDIR=/drone/dist/$$BRANCH-$$BUILD_NUMBER
    volumes:
      - /home/gres/Projects/filemanager/dist:/drone/dist
    commands:
      - cd /base/build
      - /base/src/utils/make_appimage.sh
      - mv *.AppImage /drone/dist
    when:
      branch: [release/*, master, feature/ci-*]
