workspace:
  base: /base
  path: src
  
pipeline:
  test:
    image: gres/multidir:precise
    commands:
      - cd /build
      - /base/src/utils/make_ubuntu.sh

  pack:
    image: gres/multidir:precise
    privileged: true
    devices:
      - /dev/fuse
    volumes:
      - /home/gres/Projects/filemanager/dist:/drone/dist
    commands:
      - cd /build
      - /base/src/utils/make_appimage.sh
      - mv *.AppImage /drone/dist
    when:
      branch: [release/*, master, feature/ci-*]
