workspace:
  base: /base
  path: src
  
pipeline:
  test:
    image: gres/multidir:precise
    volumes:
      - /home/gres/Projects/filemanager/dist:/drone/dist
    commands:
      - cd /build
      - /base/src/utils/precise/build.sh
      - mv `ls *.appimage` /drone/dist/$(basename `ls *.appimage` .appimage)-$DRONE_BRANCH.appimage
