workspace:
  base: /base
  path: src
  
pipeline:
  test:
    image: gres/multidir:precise
    commands:
      - cd /build
      - /base/src/utils/precise/build.sh

  pack:
    image: gres/multidir:precise
    volumes:
      - /home/gres/Projects/filemanager/dist:/drone/dist
    commands:
      - cd /build
      - mv *.appimage /drone/dist
    when:
      branch: [release/*, master, feature/ci-*]
