workspace:
  base: /base
  path: src
  
pipeline:
  test:
    image: gres/multidir:precise
    volumes:
      - /home/gres/Projects/filemanager/dist:/drone/dist
    commands:
      - cd /build
      - /base/src/utils/precise/build.sh
      - for f in `ls multidir-*.appimage`; do mv $f /drone/dist/$(basename $f .appimage)-$DRONE_BRANCH.appimage; done
