language: cpp

dist: precise
sudo: required

git:
  depth: 1

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: precise
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./utils/osx/prepare.sh & sudo ./utils/osx/prepare.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./utils/precise/prepare.sh & sudo ./utils/precise/prepare.sh; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./utils/osx/build.sh & ./utils/osx/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./utils/precise/build.sh & ./utils/precise/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "K+jeDetf7fsc3N8bknZ9NNNfxNcm/r2+BAGMPr/sBGaPxMWhy0XW1Zj5w12j2MfQAVRB1ttRzwchmH3AfPZh0mRH4znjxdNlPY9zYv0vMC+KzsMaa51/3CgP6z3r0xq1X8HXaLsZt59qyqNBV/6vPiRSChRJmOUcyDkftlcCMERp2vjToW3BZDCx81Y8LoKsB+2xj9s9YpJhCNpiAydcfeTjd7uVoLQjJD4ZuMHBVLMjTDA9jUlhokHQiD4qo+SWfeRvSUPx6CIGVTFy4QFSGKz2voqk+iu+78K8Tux1bZOOgzbT/L66UP8BnfILPfqihRLs1IWHic3478/WE6+sZqjqhpzTRwd8ns52EEBpkrBTDlsClMHS8gjLN7jwiJCR+U5mHjTn4gkk99hu9GSQ/gjrdcNrD/+iqceKV5U0P6e6qirrQSJI1/kLMOroqMvW+zTYhh5tbYzpXagxSEihEjeH1MuBzV2GuwkOuRZJ7L16UZVx9xR2+nQWCnlHbVcd94mud1ost8VEBN+yo7qypsePJpXp1FxkhfDz17D+J+r6UIqiFshE3nAJw4+7hQefs/39rmeguT+0MRbFGGTrVIS3C8EuIODuBAFUdiRkMXmMuaG2rPEuJ5kT8eA029oPD3JLNp8GdmWiZolUruMkPzBq8s2rrLjM7+rNe5G33oI="
    file_glob: true
    file: "multidir-*.appimage"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: "K+jeDetf7fsc3N8bknZ9NNNfxNcm/r2+BAGMPr/sBGaPxMWhy0XW1Zj5w12j2MfQAVRB1ttRzwchmH3AfPZh0mRH4znjxdNlPY9zYv0vMC+KzsMaa51/3CgP6z3r0xq1X8HXaLsZt59qyqNBV/6vPiRSChRJmOUcyDkftlcCMERp2vjToW3BZDCx81Y8LoKsB+2xj9s9YpJhCNpiAydcfeTjd7uVoLQjJD4ZuMHBVLMjTDA9jUlhokHQiD4qo+SWfeRvSUPx6CIGVTFy4QFSGKz2voqk+iu+78K8Tux1bZOOgzbT/L66UP8BnfILPfqihRLs1IWHic3478/WE6+sZqjqhpzTRwd8ns52EEBpkrBTDlsClMHS8gjLN7jwiJCR+U5mHjTn4gkk99hu9GSQ/gjrdcNrD/+iqceKV5U0P6e6qirrQSJI1/kLMOroqMvW+zTYhh5tbYzpXagxSEihEjeH1MuBzV2GuwkOuRZJ7L16UZVx9xR2+nQWCnlHbVcd94mud1ost8VEBN+yo7qypsePJpXp1FxkhfDz17D+J+r6UIqiFshE3nAJw4+7hQefs/39rmeguT+0MRbFGGTrVIS3C8EuIODuBAFUdiRkMXmMuaG2rPEuJ5kT8eA029oPD3JLNp8GdmWiZolUruMkPzBq8s2rrLjM7+rNe5G33oI="
    file_glob: true
    file: "multidir-*.dmg"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx

notifications:
  email:
    on_success: change
    on_failure: change
